=== jabley/volmobserverce/trunk/framework/DeviceRepository-Open/subsystems/device/main/api/java/com/volantis/devrep/device/api/xml/schema/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Paul Duffin (Volantis Systems Ltd) -->
<xs:schema targetNamespace="http://www.volantis.com/xmlns/device-repository/device" xmlns="http://www.volantis.com/xmlns/device-repository/device" xmlns:pv="http://www.volantis.com/xmlns/device-repository/device-policies" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dev="http://www.volantis.com/xmlns/device-repository/device" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="device-core.xsd"/>
    <xs:attributeGroup name="ValueAttribute">
        <xs:attribute name="value" type="xs:string" use="optional"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="NameAttribute">
        <xs:attribute name="name" type="DevicePolicyNameType" use="required"/>
    </xs:attributeGroup>
    <xs:complexType name="FieldType">
        <xs:choice>
            <xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="ValueAttribute"/>
        <xs:attributeGroup ref="NameAttribute"/>
    </xs:complexType>
    <xs:complexType name="UninheritableValueType">
        <xs:choice>
            <xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="ValueAttribute"/>
    </xs:complexType>
    <xs:complexType name="UnnamedValueType">
        <xs:choice>
            <xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="inherit" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Indicates that the policy value is inherited from the parent device.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="ValueAttribute"/>
    </xs:complexType>
    <xs:complexType name="NamedValueType">
        <xs:complexContent>
            <xs:extension base="dev:UnnamedValueType">
                <xs:attributeGroup ref="NameAttribute"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="PolicyType">
        <xs:complexContent>
            <xs:extension base="dev:NamedValueType">
                <xs:attributeGroup ref="CommonAttributes"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="device">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="policies"/>
            </xs:sequence>
            <xs:attributeGroup ref="CommonAttributes"/>
            <xs:attribute name="name" type="DeviceNameType" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="policies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="policy" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="PolicyNameKey">
            <xs:selector xpath="dev:policy"/>
            <xs:field xpath="@name"/>
        </xs:key>
    </xs:element>
    <xs:element name="policy">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="dev:PolicyType">
                    <xs:sequence>
                        <xs:element name="standard" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>The standard value of this policy. This is only present if the customer has changed the value of a standard policy of a standard device.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="policy" type="dev:PolicyType" minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="UniquePolicyValue">
            <xs:selector xpath="./dev:value"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="UniquePolicyField">
            <xs:selector xpath="./dev:field"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="field" type="dev:FieldType">
        <xs:unique name="UniqueFieldValue">
            <xs:selector xpath="./dev:value"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 13-May-04	4351/1	allan	VBM:2004051011 Fix NullPointerException in StandardElementHandler

 ===========================================================================
-->

=== jabley/volmobserverce/MCS/product-tests/impl/src/test/resources/com/volantis/mcs/xdime/integration/webapp/WEBINF/test-devices/standard/devices/XDIME.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<device xmlns="http://www.volantis.com/xmlns/device-repository/device" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.volantis.com/xmlns/device-repository/device http://www.volantis.com/schema/device-repository/v3.0/device.xsd">
    <policies>
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="portability" value="30" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="width" value="267" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="msvid" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pjpeginpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="preferredmessageprotocol" value="MHTML" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="vscroll" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="aggregation" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="rendermode" value="rgb" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="cookies" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="viewinbright" value="false" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="onehanded" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="microphone" value="false" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="preferredimagetype" value="JPEG" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pageup" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="flashinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pixeldepth" value="24" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="realvidinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="sec.id.header" value="accept" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pnginpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="baudioinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="exclusivity" value="group" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="sound" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="jscriptversion" value="1.1" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="realaudioinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="qtimeinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="swinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="jpeginpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pixelsx" value="750" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="sslkeystrng" value="56" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="protocol">
            <device:value>-XDIME-Protocol-</device:value>
        </device:policy>
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="download" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="css.inline.import" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="mhtmlprotocol">
            <device:value>HTMLVersion3_2</device:value>
        </device:policy>
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="fullpixelsx" value="800" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="transparent" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="numpalette" value="0" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="agifinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="javaapplets" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="height" value="200" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="ssversion">
            <device:value>CSS2</device:value>
        </device:policy>
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="adcpm32inpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="sslvers" value="3" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pixelsy" value="550" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="pagedown" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="bookmarks" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="msmainpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="javascript" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="viewindark" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="stylesheets" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="gifinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="wavinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="java" value="J2SE" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="activesky" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="kbusability" value="80" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="kbdtype" value="full" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="fullpixelsy" value="600" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="ssl" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="viewdist" value="400" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="UAProf.CcppAccept">
            <device:value>text/html</device:value>
            <device:value>image/jpeg</device:value>
            <device:value>image/png</device:value>
            <device:value>image/gif</device:value>
        </device:policy>
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="msvidinpage" value="true" />
        <device:policy xmlns:device="http://www.volantis.com/xmlns/device-repository/device" name="supports.client.framework" value="false">
            <device:standard />
        </device:policy>
        <policy name="x-css.default.rules" value="
        spatial{display:table}
        spatial-row{display:table-row}
        spatial-cell{display:table-cell}
        grid{display:table}
        grid-row{display:table-row}
        grid-cell{display:table-cell}
        pane{display:block}
        inclusion{display:block}"/>
        <policy name="x-css.properties.background-attachment.initial-value" value="&lt;standard&gt;"/>
        <policy name="x-css.properties.background-color.initial-value" value="&lt;standard&gt;"/>
        <policy name="x-css.properties.background-image.initial-value" value="&lt;standard&gt;"/>
        <policy name="x-css.properties.background-position.initial-value" value="&lt;standard&gt;"/>
