=== jabley/volmobserverce/trunk/MCS/oldtests/impl/src/test/resources/com/volantis/mcs/eclipse/ab/editors/dom/script.dtd
<!-- This is the common DTD for all scenario DTDs -->

<!-- A script is made up of the following top-level directives -->
<!ELEMENT script (applySelection|amendProxy|checkProxieds|checkProxy|
                  detailsGetters|selectionHierarchy|updateAttribValue|
                  updateElementName|updateSelection)*>
<!ATTLIST script title CDATA #REQUIRED>


<!-- TOP-LEVEL (DIRECTIVE) DEFINITIONS -->

<!-- This directive causes the specified set of elements to be passed to
the selection event handling method of the top-level ProxyElement -->
<!-- NB it supports "dual names" to support setName name changing -->
<!ELEMENT applySelection (topA|topB)*>
<!ATTLIST applySelection expected CDATA #REQUIRED>

<!-- This directive checks the proxied elements retrived from the details
object for the ProxyElement with the specified name against what is in
script (with optional recursion). If callCount is present, a check is made
for the number of times setProxiedElements has been called: TODO explain -->
<!ELEMENT checkProxieds ANY>
<!ATTLIST checkProxieds name CDATA #REQUIRED recurse (y|n) #REQUIRED
          callCount CDATA #IMPLIED reason (a|av|e|en|n) #IMPLIED
          expected CDATA #REQUIRED>

<!-- This directive checks the the ProxyElement with the specified name
against what is in script (with optional recursion) -->
<!ELEMENT checkProxy ANY>
<!ATTLIST checkProxy name CDATA #REQUIRED recurse (y|n) #REQUIRED
          expected CDATA #REQUIRED>

<!-- This directive sets the returns of the getters in ProxyElementDetails
for the named ProxyElement(Details) -->
<!ELEMENT detailsGetters (attributeNames?,elementName?)>
<!ATTLIST detailsGetters name CDATA #REQUIRED expected CDATA #REQUIRED>

<!-- Makes an c(reation) to or d(eletion) from the hierarchy passed to
applySelection: typically this will be followed by one or more of the
checkXxxx directives -->
<!ELEMENT selectionHierarchy (pathToSelection)>
<!ATTLIST selectionHierarchy action (c|d) #REQUIRED expected CDATA #REQUIRED>

<!-- This directive causes a updateValue to be called on the specified
attribute (which must exist) within the specified element -->
<!ELEMENT updateAttribValue (proxy|pathToSelection)>
<!ATTLIST updateAttribValue name CDATA #REQUIRED value CDATA #REQUIRED
          expected CDATA #REQUIRED>

<!-- This directive causes a setName to be called on the specified
<TODO explain> -->
<!ELEMENT updateElementName (proxy|pathToSelection)>
<!ATTLIST updateElementName newName CDATA #REQUIRED expected CDATA #REQUIRED>

<!-- This directive causes a specified set of elements to become selected
     within the previously defined applySelection hierarchy -->
<!ELEMENT updateSelection (xpath)*>
<!ATTLIST updateSelection expected CDATA #REQUIRED>

<!-- This directive connects or disconnects a proxy from its 'parent' proxy -->
<!ELEMENT amendProxy EMPTY>
<!ATTLIST amendProxy
          name CDATA #REQUIRED
          action (connect|disconnect) #REQUIRED
          expected CDATA #REQUIRED>

<!-- NON-TOP-LEVEL (SUPPORTING) ELEMENT DEFINITIONS -->

<!-- Defines a set of attribute names -->
<!ELEMENT attributeNames (#PCDATA)>
<!ATTLIST attributeNames
    n1 CDATA #IMPLIED n2 CDATA #IMPLIED n3 CDATA #IMPLIED n4 CDATA #IMPLIED
    n5 CDATA #IMPLIED n6 CDATA #IMPLIED n7 CDATA #IMPLIED n8 CDATA #IMPLIED>

<!-- Defines an element name -->
<!ELEMENT elementName (#PCDATA)>
<!ATTLIST elementName name CDATA #REQUIRED>


<!-- UTILITY ELEMENTS -->

<!ELEMENT null EMPTY>

<!ELEMENT proxy (#PCDATA)>
<!ATTLIST proxy name CDATA #REQUIRED>

<!ELEMENT pathToSelection (#PCDATA)>
<!ATTLIST pathToSelection context CDATA #REQUIRED xpath CDATA #REQUIRED>

<!ELEMENT xpath EMPTY>
<!ATTLIST xpath path CDATA #REQUIRED>

<!-- DATA MODEL FOR ALL TESTS -->

<!-- This is the "top-level" proxy element, with 2 names for renaming -->
<!ELEMENT topA (middleA|middleB|arbitrary)*>
<!ATTLIST topA top1 CDATA #IMPLIED top2 CDATA #IMPLIED top3 CDATA #IMPLIED
               top4 CDATA #IMPLIED top5 CDATA #IMPLIED top6 CDATA #IMPLIED>
<!ELEMENT topB (middleA|middleB|arbitrary)*>
<!ATTLIST topB top1 CDATA #IMPLIED top2 CDATA #IMPLIED top3 CDATA #IMPLIED
               top4 CDATA #IMPLIED top5 CDATA #IMPLIED top6 CDATA #IMPLIED>

<!-- This is the "middle-level" proxy element, with 2 names for renaming -->
<!ELEMENT middleA (bottomA|bottomB|arbitrary)*>
<!ATTLIST middleA middle1 CDATA #IMPLIED middle2 CDATA #IMPLIED
                  middle3 CDATA #IMPLIED middle4 CDATA #IMPLIED
                  middle5 CDATA #IMPLIED middle6 CDATA #IMPLIED>
<!ELEMENT middleB (bottomA|bottomB|arbitrary)*>
<!ATTLIST middleB middle1 CDATA #IMPLIED middle2 CDATA #IMPLIED
                  middle3 CDATA #IMPLIED middle4 CDATA #IMPLIED
                  middle5 CDATA #IMPLIED middle6 CDATA #IMPLIED>

<!-- This is the "bottom-level" proxy element, with 2 names for renaming -->
<!ELEMENT bottomA (arbitrary*)>
<!ATTLIST bottomA bottom1 CDATA #IMPLIED bottom2 CDATA #IMPLIED
                  bottom3 CDATA #IMPLIED bottom4 CDATA #IMPLIED
                  bottom5 CDATA #IMPLIED bottom6 CDATA #IMPLIED>
<!ELEMENT bottomB (arbitrary*)>
<!ATTLIST bottomB bottom1 CDATA #IMPLIED bottom2 CDATA #IMPLIED
                  bottom3 CDATA #IMPLIED bottom4 CDATA #IMPLIED
                  bottom5 CDATA #IMPLIED bottom6 CDATA #IMPLIED>

<!-- This is an arbitrary "non-target" element -->
<!ELEMENT arbitrary ANY>
<!ATTLIST arbitrary arbitrary1 CDATA #IMPLIED arbitrary2 CDATA #IMPLIED>

<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 29-Sep-04	5674/1	philws	VBM:2004080406 Fix proxy element hierarchical source event problem seen with undoing a swap action on the layout editor

 18-Dec-03	2137/12	richardc	VBM:2003120402 Extra tests for event non-generation

 17-Dec-03	2137/10	richardc	VBM:2003120402 Version for initial review (code and test harness)

 ===========================================================================
-->

=== jabley/volmobserverce/MCS/oldtests/impl/src/test/resources/com/volantis/mcs/eclipse/ab/editors/dom/script.40.xml
<?xml version="1.0" standalone="no"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<!DOCTYPE script SYSTEM "script.dtd">

<script title="Make sure that multi-level selections don't break when deletions occur">
    <!-- This test operates with a single level proxy that can have selections
         from multiple levels within the DOM to demonstrate that the proxy
         correctly detects and handles the situation where a deletion event
         occurs for the selected child and is correctly ignored when reported
         from the selected ancestor (parent in this case). -->

    <!-- Clear any current selection so that the proxy hierarchy can be
         amended (proxy hierarchies can not be modified with a non-null
         selection) -->
    <applySelection expected="Empty selection"/>

    <!-- Disconnect the middleA proxy to support this strange "multi-level"
         selection scenario -->
    <amendProxy name="middleA"
        action="disconnect"
        expected="Leave only one proxy in the proxy hierarchy"/>

    <!-- Start with a multi-level hierarchy -->
    <applySelection
        expected="Define a selectable hierarchy">
        <topA top1="top level">
            <middleA middle1="nested middle" />
        </topA>
    </applySelection>

    <!-- Now reset the selections within the applied selection -->
    <updateSelection expected="New selection of parent and child">
        <xpath path="topA"/>
        <xpath path="topA/middleA"/>
    </updateSelection>

    <!-- Now delete the nested middleA. It is here that the problem in
         VBM 2004080406 used to occur -->
    <selectionHierarchy action="d" expected="The middle element deleted">
        <pathToSelection context="topA" xpath="middleA"/>
    </selectionHierarchy>

    <!-- Clear any current selection so that the proxy hierarchy can be
         amended (proxy hierarchies can not be modified with a non-null
         selection) -->
    <applySelection expected="Empty selection"/>

    <!-- Now re-connect the middleA proxy in case other tests follow this
         one (they continue with the current state) -->
    <amendProxy name="middleA"
        action="connect"
        expected="Reset the proxy hierarchy to the initial condition"/>
</script>

<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 29-Sep-04	5674/1	philws	VBM:2004080406 Fix proxy element hierarchical source event problem seen with undoing a swap action on the layout editor

 ===========================================================================
-->

=== jabley/volmobserverce/trunk/MCS/oldtests/impl/src/test/resources/com/volantis/mcs/eclipse/ab/editors/dom/script.04.xml
<?xml version="1.0" standalone="no"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<!DOCTYPE script SYSTEM "script.dtd">

<script title="Reset supported attributes set and re-select with data">

<detailsGetters name="topA"
  expected="Restore to original set">
  <attributeNames n1="top2" n2="top1">
  </attributeNames>
</detailsGetters>

<detailsGetters name="middleA"
  expected="Restore to original set">
  <attributeNames n1="middle1" n2="middle2">
  </attributeNames>
</detailsGetters>

<detailsGetters name="bottomA"
  expected="Restore to original set">
  <attributeNames n1="bottom2" n2="bottom1">
  </attributeNames>
</detailsGetters>

<applySelection
  expected="Selection with supp/unsupp attributes">
  <topA top3="notSupported" top2="supported">
    <middleA middle1="supported" middle3="notSupported">
      <bottomA bottom6="notSupported" bottom2="supported">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxieds name="topA" recurse="n"
  expected="as selection">
  <topA top3="notSupported" top2="supported">
  </topA>
</checkProxieds>

<checkProxy name="topA" recurse="n"
  expected="one empty, one non-empty">
  <topA top2="supported" top1="">
  </topA>
</checkProxy>

<checkProxieds name="middleA" recurse="n"
  expected="as selection">
  <middleA middle1="supported" middle3="notSupported">
  </middleA>
</checkProxieds>

<checkProxy name="middleA" recurse="n"
  expected="one empty, one non-empty">
  <middleA middle2="" middle1="supported">
  </middleA>
</checkProxy>

<checkProxieds name="bottomA" recurse="n"
  expected="as selection">
  <bottomA bottom6="notSupported" bottom2="supported">
  </bottomA>
</checkProxieds>

<checkProxy name="bottomA" recurse="n"
  expected="one empty, one non-empty">
  <bottomA bottom1="" bottom2="supported">
  </bottomA>
</checkProxy>


<!-- End script -->
</script>



<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 18-Dec-03	2137/4	richardc	VBM:2003120402 Extra tests for event non-generation

 17-Dec-03	2137/2	richardc	VBM:2003120402 Version for initial review (code and test harness)

 ===========================================================================
-->

=== jabley/volmobserverce/trunk/MCS/oldtests/impl/src/test/resources/com/volantis/mcs/eclipse/ab/editors/dom/script.05.xml
<?xml version="1.0" standalone="no"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<!DOCTYPE script SYSTEM "script.dtd">

<script title="Selection-driven aggregation value tests (on bottom)">

<applySelection
  expected="Simplest possible non-empty aggregation">
  <topA>
    <middleA>
      <bottomA bottom1="aggOK" bottom3="notSupp" bottom2="differs-1">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom2="differs-2" bottom3="notSupp" bottom1="aggOK">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="one aggregated value">
  <bottomA bottom1="aggOK" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because first one empty">
  <topA>
    <middleA>
      <bottomA bottom1="">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because second one empty">
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because last one empty">
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because second one different">
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg2">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because first one missing">
  <topA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because second one missing">
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Empty aggregation because last one missing">
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="noAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="" bottom2="">
  </bottomA>
</checkProxy>

<applySelection
  expected="Confidence test that it DOES work when all there">
  <topA>
    <middleA>
      <bottomA bottom1="yesAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="yesAgg">
      </bottomA>
    </middleA>
  </topA>
  <topA>
    <middleA>
      <bottomA bottom1="yesAgg">
      </bottomA>
    </middleA>
  </topA>
</applySelection>

<checkProxy name="bottomA" recurse="n"
  expected="check bottom1 still empty">
  <bottomA bottom1="yesAgg" bottom2="">
  </bottomA>
</checkProxy>


<!-- End script -->
</script>



<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 18-Dec-03	2137/3	richardc	VBM:2003120402 Extra tests for event non-generation

 17-Dec-03	2137/1	richardc	VBM:2003120402 Version for initial review (code and test harness)

 ===========================================================================
-->
