=== jabley/volmobserverce/trunk/DeviceRepository/device/api/src/main/resources/com/volantis/devrep/device/api/xml/schema/device-policy-definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<xs:schema targetNamespace="http://www.volantis.com/xmlns/device-repository/policy-definitions" xmlns="http://www.volantis.com/xmlns/device-repository/policy-definitions" xmlns:pd="http://www.volantis.com/xmlns/device-repository/policy-definitions" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="device-core.xsd"/>
    <xs:annotation>
        <xs:documentation>Common Types</xs:documentation>
    </xs:annotation>
    <xs:simpleType name="CategoryNameType">
        <xs:restriction base="xs:NCName"/>
    </xs:simpleType>
    <xs:simpleType name="CategoryPrefixType">
        <xs:restriction base="xs:NCName"/>
    </xs:simpleType>
    <xs:annotation>
        <xs:documentation>Elements</xs:documentation>
    </xs:annotation>
    <xs:element name="definitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="types" minOccurs="0"/>
                <xs:element ref="category" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="UniquePolicy">
            <xs:selector xpath="pd:category/pd:policy"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:key name="UniqueCategory">
            <xs:selector xpath="pd:category"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:unique name="UniqueCategoryPrefix">
            <xs:selector xpath="pd:category"/>
            <xs:field xpath="@prefix"/>
        </xs:unique>
        <xs:key name="PredefinedTypeName">
            <xs:selector xpath="pd:types/pd:type"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="PredefinedTypeReference" refer="PredefinedTypeName">
            <xs:selector xpath=".//pd:type"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
    <xs:annotation>
        <xs:documentation>Category definitions</xs:documentation>
    </xs:annotation>
    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="policy" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attributeGroup ref="CommonAttributes"/>
            <xs:attribute name="name" type="CategoryNameType" use="required"/>
            <xs:attribute name="prefix" type="CategoryPrefixType" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="policy">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="type"/>
                <xs:group ref="CCPPVocabularyGroup" minOccurs="0"/>
            </xs:sequence>
            <xs:attributeGroup ref="CommonAttributes"/>
            <xs:attribute name="name" type="DevicePolicyNameType" use="required"/>
            <xs:attribute name="ccppVocabulary" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="none"/>
                        <xs:enumeration value="UAProf"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:group name="CCPPVocabularyGroup">
        <xs:choice>
            <xs:element ref="UAProf"/>
        </xs:choice>
    </xs:group>
    <xs:annotation>
        <xs:documentation>UAProf Specific Elements</xs:documentation>
    </xs:annotation>
    <xs:simpleType name="UAProfAttributeName">
        <xs:annotation>
            <xs:documentation>Specifies the legal values for UAProf attribute names.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="UAProf">
        <xs:complexType>
            <xs:attribute name="attribute" type="UAProfAttributeName" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:annotation>
        <xs:documentation>Policy Type</xs:documentation>
    </xs:annotation>
    <xs:annotation>
        <xs:documentation>Policy Definitions</xs:documentation>
    </xs:annotation>
    <xs:element name="type">
        <xs:complexType>
            <xs:group ref="AllPolicyTypes" minOccurs="0"/>
            <xs:attribute name="ref" type="TypeName" use="optional">
                <xs:annotation>
                    <xs:documentation>References a predefined type. If this attribute is specified then the body content must be empty.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="boolean"/>
    <xs:element name="int"/>
    <xs:element name="range">
        <xs:complexType>
            <xs:attribute name="minInclusive" type="xs:int" use="required"/>
            <xs:attribute name="maxInclusive" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="selection">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="keyword">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="(\p{L}|\p{N}|[\-/_. ()])+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="text"/>
    <xs:annotation>
        <xs:documentation>Predefined Types</xs:documentation>
    </xs:annotation>
    <xs:simpleType name="TypeName">
        <xs:restriction base="xs:NCName"/>
    </xs:simpleType>
    <xs:element name="types">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:group ref="AllPolicyTypes"/>
                        <xs:attribute name="name" type="TypeName" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:annotation>
        <xs:documentation>Structured Types</xs:documentation>
    </xs:annotation>
    <xs:element name="structure">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="field" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type">
                                <xs:complexType>
                                    <xs:group ref="SimplePolicyTypes"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="FieldNameType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="FieldName">
            <xs:selector xpath="pd:field"/>
            <xs:field xpath="@name"/>
        </xs:key>
    </xs:element>
    <xs:element name="emulateEmphasisTag"/>
    <xs:annotation>
        <xs:documentation>Composite Types</xs:documentation>
    </xs:annotation>
    <xs:element name="orderedSet">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="SimplePolicyTypes"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="unorderedSet">
        <xs:complexType>
            <xs:group ref="SimplePolicyTypes"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="SimplePolicyTypes">
        <xs:choice>
            <xs:element ref="boolean"/>
            <xs:element ref="int"/>
            <xs:element ref="range"/>
            <xs:element ref="text"/>
            <xs:element ref="selection"/>
            <xs:element ref="emulateEmphasisTag"/>
        </xs:choice>
    </xs:group>
    <xs:group name="CompositePolicyTypes">
        <xs:choice>
            <xs:element ref="orderedSet"/>
            <xs:element ref="unorderedSet"/>
            <xs:element ref="structure"/>
        </xs:choice>
    </xs:group>
    <xs:group name="AllPolicyTypes">
        <xs:choice>
            <xs:group ref="SimplePolicyTypes"/>
            <xs:group ref="CompositePolicyTypes"/>
        </xs:choice>
    </xs:group>
</xs:schema>

<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 21-Apr-04	3016/2	adrian	VBM:2004021301 Fixed merge problems with updated XMLDeviceRepositoryAccessor

 19-Feb-04	3018/1	adrian	VBM:2004021302 Updated write methods for device repository accessor

 01-Apr-04	3602/1	doug	VBM:2004030402 Added a StructurePolicyValueModifier

 19-Dec-03	2217/1	tony	VBM:2003120804 Migration now supports in-process validation

 ===========================================================================
-->

=== jabley/volmobserverce/MCS/oldtests/impl/src/test/resources/com/volantis/devrep/prof/repository/devices/update/client/definitionsTest1orig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->

<definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.volantis.com/xmlns/device-repository/policy-definitions" xsi:schemaLocation="http://www.volantis.com/xmlns/device-repository/policy-definitions http://www.volantis.com/schema/device-repository/v3.0/device-policy-definitions.xsd">
    <types>
        <type name="EmulateEmphasisTag">
            <structure>
                <field name="enable">
                    <type>
                        <boolean/>
                    </type>
                </field>
                <field name="prefix">
                    <type>
                        <text/>
                    </type>
                </field>
                <field name="suffix">
                    <type>
                        <text/>
                    </type>
                </field>
                <field name="altTag">
                    <type>
                        <text/>
                    </type>
                </field>
            </structure>
        </type>
    </types>
    <category name="location">
        <policy name="mapdatum">
            <type>
                <selection>
                    <keyword>WGS-84</keyword>
                </selection>
            </type>
        </policy>
    </category>
    <category name="misc" prefix="misc">
        <policy name="wibble">
            <type>
                <selection>
                    <keyword>none</keyword>
                </selection>
            </type>
        </policy>
    </category>
</definitions>
<!--
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 28-Apr-05	7834/1	matthew	VBM:2005041518 Add support for policy and category definition events in the device repository merge

 ===========================================================================
-->
